import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        {/* Background Blur Effect */}
        <div className="blur-bg">
          <div className="blur-circle red"></div>
          <div className="blur-circle blue"></div>
          <div className="blur-circle dark-blue"></div>
        </div>

        {/* Content */}
        <main className="relative z-10 min-h-screen">{children}</main>
      </body>
    </html>
  );
}
